### ISSUE TITLE
Getting python error 

### ISSUE THREAD

**Issue by Saikatsaha1996** [DumprX/DumprX#10]
![IMG20230513153806](https://github.com/DumprX/DumprX/assets/72664192/07385794-fc88-4f7d-8320-5f7a6a2f1dd5)

Help wanted

**Comment by Iascker** [comment]
Any temporary workaround?

**Comment by Saikatsaha1996** [comment]
> Any temporary workaround?

Nah No system/vendor/product build*.prop found, pushing cancelled.

**Comment by Sushrut1101** [comment]
This is not a DumprX issue, please report it to aospdtgen
