### ISSUE TITLE
You are attempting to check in one or more blobs which exceed the 100.0MiB limit

### ISSUE THREAD

**Issue by VanVuong41429** [DumprX/DumprX#25]
remote: GitLab: You are attempting to check in one or more blobs which exceed the 100.0MiB limit:        
remote: 
remote: - 733315aecd6ac3eaf5dce93eed8e20dd4df9edc8 (105.13 MiB)         
remote: - 73ad529044020d4ce2df811e56b7034af3cf9be4 (100.79 MiB)         
remote: - 862d7ac243eb494f07adeaf06367be2ffaa0f014 (137.89 MiB)         
remote: - df3502098a42c6c0b334f54a84b602c19a6c4233 (242.29 MiB)         
remote: - 080c9ecfccf6c005b7b81ed4aa30d8fc7acf4e5d (109.45 MiB)         
remote: 
remote: To resolve this error, you must either reduce the size of the above blobs, or utilize LFS.        
remote: You may use "git ls-tree -r HEAD | grep $BLOB_ID" to see the file path.        
remote: Please refer to https://gitlab.com/help/user/free_push_limit and        
remote: https://gitlab.com/help/administration/settings/account_and_limit_settings        
remote: for further information.        
To gitlab.com:dumprx-by-me/motorola/devon.git
 ! [remote rejected] user-12-S2SNS32.34-72-31-2-b63a6-release-keys -> user-12-S2SNS32.34-72-31-2-b63a6-release-keys (pre-receive hook declined)
error: failed to push some refs to 'gitlab.com:dumprx-by-me/motorola/devon.git'

**Comment by SuperiorPsycho** [comment]
@Sushrut1101 Accha

**Comment by JEFFERSON-FERREIRA-LIMA** [comment]
This should resolve:
https://docs.gitlab.com/ee/topics/git/lfs/index.html

See the "Enable Git LFS" for a project Section

I hope I have helped.

**Comment by Sushrut1101** [comment]
Fixed

**Comment by prakyath-07** [comment]
1. Install Git LFS (if not already):
        git lfs install
        
2. Track the file type or specific file (example: all .mp4 files or just one file):
        git lfs track "*.mp4"
        # or
        git lfs track "path/to/largefile.ext"
        
3. Re-add and recommit the large file:
        git rm --cached path/to/largefile.ext
        git add path/to/largefile.ext
        git commit -m "Add large file via LFS"

4. Push:
        git push origin main
