### ISSUE TITLE
when extract,it showed 'no space left on device'

### ISSUE THREAD

**Issue by Ichigokano** [DumprX/DumprX#4]
Working with miui_RUBENS_V13.0.23.0.SLNCNXM_487cdb90aa_12.0.zip

Extracting firmware on: /home/bay/android/dump/DumprX/out
AB OTA Payload Detected
Please wait while extracting payload.bin from the archive.
2022/09/24 20:31:04 write /tmp/payload_144875771.bin: no space left on device
██████████████████  ████████   bay@bay-pc 
██████████████████  ████████   ---------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: HP Pavilion Laptop 14-ce1xxx 
████████            ████████   Kernel: 5.15.65-1-MANJARO 
████████  ████████  ████████   Uptime: 3 hours, 31 mins 
████████  ████████  ████████   Packages: 1222 (pacman) 
████████  ████████  ████████   Shell: bash 5.1.16 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: Plasma 5.25.5 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   Theme: [Plasma], Breeze [GTK2/3] 
████████  ████████  ████████   Icons: [Plasma], breeze [GTK2/3] 
████████  ████████  ████████   Terminal: konsole 
                               CPU: Intel i5-8265U (8) @ 3.900GHz 
                               GPU: NVIDIA GeForce MX150 
                               GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
                               Memory: 4822MiB / 7829MiB 
                                                                                                      
No system/vendor/product build*.prop found, pushing cancelled.

**Comment by NeonzGamingYT** [comment]
@Ichigokano lol local?

**Comment by NeonzGamingYT** [comment]
check your storage

**Comment by Ichigokano** [comment]
> check your storage

100G left😂Blame manjaro?

**Comment by Sushrut1101** [comment]
This is not a DumprX Issue. Please check your available Storage!
