### ISSUE TITLE
Couldn't extract system partition by 7z. Using fsck.erofs

### ISSUE THREAD

**Issue by nguyenhung9xdev2022** [DumprX/DumprX#6]
I try extract firmware samsung galaxy A73 but it get problem. How to fix

Couldn't extract system partition by 7z. Using fsck.erofs.
erofs: cannot find valid erofs superblock
erofs: failed to read superblock
Couldn't extract system partition by fsck.erofs. Using mount loop

![196029070-f5d26268-c25e-4810-8a32-00c8e6bd7759](https://user-images.githubusercontent.com/101638735/196029205-0055b5c8-228c-4910-99e0-da7f3cbe6a65.png)

**Comment by Sushrut1101** [comment]
@nguyenhung9xdev2022 Idk why it's not working on newer Samsung Devices, will look into it magbe

**Comment by edward0181** [comment]
Wondering if you've managed to check?
